# 【多环境切换】用来配置读取哪个配置文件
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.starry.entity # 所有Entity别名类所在包
  mapper-locations: classpath:/mapper/**/*.xml # mapper映射文件
spring:
  profiles:
    active: dev
server:
  port: 8011